// ============================================================
// CONFIGURAÇÃO DO RESTAURANTE — editar aqui para mudar tudo
// ============================================================

export const config = {
  // --- IDENTIDADE ---
  name: 'Clave de Sol',
  tagline: 'Café & Restaurante • Since 1983',
  description: 'Snacks, francesinhas, mariscos, hambúrgueres e muito mais. Desde 1983 com o mesmo sabor.',

  // --- CONTACTO ---
  contact: {
    phone: '+351 252 130 781',
    whatsapp: '',
    address: 'Av. Infante Dom Henrique 76, 4480-670 Vila do Conde',
    city: 'Vila do Conde',
    googleMapsUrl: 'https://maps.google.com/?q=Av.+Infante+Dom+Henrique+76+4480-670+Vila+do+Conde',
  },

  // --- HORÁRIOS ---
  hours: [
    { days: 'Segunda', time: '08h00 – 00h00' },
    { days: 'Terça', time: 'Encerrado' },
    { days: 'Quarta a Domingo', time: '08h00 – 00h00' },
  ],

  // --- REDES SOCIAIS ---
  social: {
    instagram: 'clave_de_sol_cafe',
    facebook: '',
    tripadvisor: '',
  },

  // --- IMAGENS ---
  images: {
    logo: '/images/logo.svg',
    hero: '/images/hero.jpg',
  },

  // --- MOEDA ---
  currency: '€',

  // --- GRUPOS PRINCIPAIS ---
  menuGroups: [
    {
      id: 'snacks',
      label: 'Snacks',
      emoji: '🥖',
      description: 'Francesinhas, Hambúrgueres, Tostas, Wraps e mais',
    },
    {
      id: 'petiscos',
      label: 'Petiscos & Mar',
      emoji: '🦐',
      description: 'Entradas, Mariscos e Saladas',
    },
    {
      id: 'manha',
      label: 'Pequeno Almoço',
      emoji: '☕',
      description: 'Torradas, Croissants e Menu Kids',
    },
    {
      id: 'bebidas',
      label: 'Bebidas',
      emoji: '🍺',
      description: 'Cervejas, Sangrias e mais',
    },
  ],

  // --- EMENTA ---
  menu: [
    {
      id: 'entradas',
      category: 'Entradas',
      group: 'petiscos',
      emoji: '🫒',
      items: [
        {
          id: 'couvert',
          name: 'Couvert',
          description: 'Paté de Atum, Azeitonas e Tostas',
          price: 5.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'pao-alho',
          name: 'Pão de Alho',
          description: 'Unidade',
          price: 1.30,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'recheio-sapateira',
          name: 'Recheio de Sapateira',
          description: '',
          price: 7.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'asinhas-frango',
          name: 'Asinhas de Frango',
          description: '',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'panadinhas',
          name: 'Panadinhas',
          description: '',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'moelinhas',
          name: 'Moelinhas',
          description: '',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'ovos-rotos',
          name: 'Ovos Rotos',
          description: 'Batatas fritas, Presunto, Ovos, Paprika',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/ovosrotos.png',
        },
        {
          id: 'ovos-rotos-especiais',
          name: 'Ovos Rotos Especiais',
          description: 'Batatas fritas, Bacon, Linguiça, Salsinha, Queijo, Ovos, Molho Especial',
          price: 10.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'ovos-rotos-clave',
          name: 'Ovos Rotos à Clave',
          description: 'Batatas fritas, Bacon, Ovos, Queijo, Cogumelos Frescos Salteados, Gambas Salteadas, Molho especial',
          price: 10.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
      ],
    },
    {
      id: 'mariscos',
      category: 'Mariscos',
      group: 'petiscos',
      emoji: '🦐',
      items: [
        {
          id: 'ameixoas',
          name: 'Amêijoas',
          description: '',
          price: 10.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '/images/menu/ameijoa.png',
        },
        {
          id: 'gambas-clave',
          name: 'Gambas à Clave',
          description: '',
          price: 10.00,
          tags: ['sem glúten'],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'gambas-natural',
          name: 'Gambas ao Natural',
          description: '',
          price: 9.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'percebes',
          name: 'Percebes',
          description: '',
          price: 10.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '/images/menu/percebes.png',
        },
        {
          id: 'camarao-costa',
          name: 'Camarão da Costa',
          description: '',
          price: 10.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'navalheiras',
          name: 'Navalheiras (kg)',
          description: '',
          price: 35.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'sapateira-recheada',
          name: 'Sapateira Recheada',
          description: 'Unidade',
          price: 20.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'misto-marisco',
          name: 'Misto de Marisco',
          description: 'Sapateira Recheada, Gamba ao Natural, Mexilhão, Meia Concha, Percebes, Camarão da Costa, Búzios, Salada do Mar, Molho Vinagrete e Molho Cocktail',
          price: 50.00,
          tags: ['sem glúten'],
          available: true,
          featured: true,
          image: '/images/menu/mistomarisco.png',
        },
      ],
    },
    {
      id: 'snack',
      category: 'Snack',
      group: 'snacks',
      emoji: '🥖',
      items: [
        {
          id: 'trinchadinha',
          name: 'Trinchadinha',
          description: '',
          price: 5.50,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/trinchadinha.png',
        },
        {
          id: 'bao-camarao',
          name: 'Bão de Camarão',
          description: '',
          price: 0.00,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/baocamarao.png',
        },
        {
          id: 'francesinha-normal-clave',
          name: 'Francesinha Normal ó Clave',
          description: 'Queijo, Fiambre, Chouriço, Ketchup, Maionese, Coberto com Queijo, Molho Especial e Batata frita',
          price: 9.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'poveira-trinchada',
          name: 'Poveira Trinchada',
          description: 'Queijo, Fiambre, Linguiça, Mostarda, Ketchup, Maionese',
          price: 5.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'francesinha-poveira-clave',
          name: 'Francesinha Poveira à Clave',
          description: 'Queijo, Fiambre, Linguiça, Mostarda, Ketchup, Maionese, Coberto com Queijo, Molho Especial e Batata frita',
          price: 9.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'cachorro-normal',
          name: 'Cachorro Normal',
          description: 'Queijo, Fiambre, Salsicha, Mostarda, Ketchup, Maionese',
          price: 5.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'cachorro-clave',
          name: 'Cachorro Normal ó Clave',
          description: 'Queijo, Fiambre, Salsicha, Mostarda, Ketchup, Maionese, Coberto com Queijo, Molho Especial e Batata frita',
          price: 9.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'francesinha-esp-lombo',
          name: 'Francesinha Especial — Bife de Lombo',
          description: 'Queijo, Fiambre, Chouriço, Bife Lombo, Coberto com Queijo, Ovo, Molho Especial e Batata frita',
          price: 13.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'meia-francesinha-lombo',
          name: 'Meia Francesinha Especial — Bife de Lombo',
          description: 'Queijo, Fiambre, Chouriço, Bife Lombo, Coberto com Queijo, Ovo, Molho Especial e Batata frita',
          price: 10.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'francesinha-esp-frango',
          name: 'Francesinha Especial — Bife de Frango',
          description: 'Queijo, Fiambre, Chouriço, Bife de Frango, Coberto com Queijo, Ovo, Molho Especial e Batata frita',
          price: 12.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'meia-francesinha-frango',
          name: 'Meia Francesinha Especial — Bife de Frango',
          description: 'Queijo, Fiambre, Chouriço, Bife de Frango, Coberto com Queijo, Ovo, Molho Especial e Batata frita',
          price: 9.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'po',
          name: 'P.O.',
          description: 'Queijo, Presunto e Ovo',
          price: 4.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'prego-pao-lombo',
          name: 'Prego em Pão com Bife do Lombo',
          description: 'Bola de Caco, Bife do Lombo, Queijo e Fiambre',
          price: 9.00,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/prego_pao.png',
        },
        {
          id: 'prego-pao-cogumelos',
          name: 'Prego em Pão de Cogumelos',
          description: 'Bola de Caco, Bife do Lombo, Cogumelos Salteados, Queijo e Molho de Alho',
          price: 10.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'prego-pao-clave',
          name: 'Prego em Pão à Clave',
          description: 'Bola de Caco, Manteiga de Alho, Bife do Lombo, Ovo, Queijo e Bacon',
          price: 10.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'prego-prato-lombo',
          name: 'Prego em Prato com Bife do Lombo',
          description: '2 Bifes do Lombo, Ovo, Batata Frita, Alface e Tomate',
          price: 12.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'prego-prato-frango',
          name: 'Prego em Prato de Frango',
          description: '2 Bifes de Frango, Ovo, Batata Frita, Alface e Tomate',
          price: 11.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'bife-clave',
          name: 'Bife à Clave',
          description: '2 Bifes do Lombo, Queijo, Ovo, Batata Frita e Molho Especial',
          price: 13.50,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
      ],
    },
    {
      id: 'batatas',
      category: 'Batatas',
      group: 'snacks',
      emoji: '🍟',
      items: [
        {
          id: 'dose-batata',
          name: 'Dose de Batata',
          description: '',
          price: 3.00,
          tags: ['vegan', 'sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'batata-clave',
          name: 'Dose de Batata à Clave',
          description: 'Batata Frita, Queijo e Molho Especial',
          price: 4.50,
          tags: ['vegetariano'],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'batata-chef',
          name: 'Dose de Batata à Chef',
          description: 'Batata Frita, Queijo Cheddar e Bacon',
          price: 5.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'hamburgueres',
      category: 'Hambúrgueres',
      group: 'snacks',
      emoji: '🍔',
      items: [
        {
          id: 'hamburger-pao',
          name: 'Hamburger no Pão',
          description: '200g de Carne da Casa, Queijo, Fiambre, Alface, Tomate, Ketchup, Maionese e Mostarda',
          price: 9.00,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/ppburger.png',
        },
        {
          id: 'hamburger-chef',
          name: 'Hamburger à Chef',
          description: '200g de Carne da Casa, Queijo, Bacon, Cebola Frita, Rúcula, Cogumelos Frescos Salteados, Tomate e Molho à Clave',
          price: 10.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'hamburger-especial',
          name: 'Hamburger Especial',
          description: '200g de Carne da Casa, Queijo, Fiambre, Ovo, Alface, Tomate, Ketchup, Maionese, Mostarda, Molho Especial e Batata Frita',
          price: 13.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'hamburger-john',
          name: 'Hamburger à John',
          description: '200g de Carne da Casa, Queijo Cheddar, Bacon, Ovo, Cebola Frita, Cogumelos Frescos Salteados, Rúcula e Molho Barbecue',
          price: 11.00,
          tags: [],
          available: true,
          featured: true,
          image: '',
        },
        {
          id: 'hamburger-vegetariano',
          name: 'Hamburger Vegetariano',
          description: 'Hamburger Vegetariano, Rúcula, Tomate, Cebola Frita, Cogumelos Frescos Salteados, Molho de Alho',
          price: 10.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'saladas',
      category: 'Saladas',
      group: 'petiscos',
      emoji: '🥗',
      items: [
        {
          id: 'salada-clave',
          name: 'Salada à Clave',
          description: 'Camarão, Delícias, Queijo Fresco, Ovo, Massa, Alface, Tomate e Cenoura',
          price: 8.00,
          tags: ['sem glúten'],
          available: true,
          featured: true,
          image: '/images/menu/salada.png',
        },
        {
          id: 'salada-frango',
          name: 'Salada de Frango',
          description: 'Peito de Frango, Queijo Fresco, Ovo, Massa, Alface, Tomate, Cenoura e Milho',
          price: 8.00,
          tags: [],
          available: true,
          featured: false,
          image: '/images/menu/bowlfrango.png',
        },
        {
          id: 'salada-atum',
          name: 'Salada de Atum',
          description: 'Atum, Queijo Fresco, Ovo, Massa, Alface, Tomate, Cenoura e Milho',
          price: 8.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'salada-salmao',
          name: 'Salada de Salmão',
          description: 'Salmão, Queijo Fresco, Ovo, Massa, Rúcula, Tomate, Cenoura e Milho',
          price: 8.00,
          tags: ['sem glúten'],
          available: true,
          featured: false,
          image: '/images/menu/bowlsalmao.png',
        },
      ],
    },
    {
      id: 'wraps',
      category: 'Wraps',
      group: 'snacks',
      emoji: '🌯',
      items: [
        {
          id: 'wrap-frango',
          name: 'Wrap de Frango',
          description: 'Peito de Frango, Queijo Cheddar, Cebola Frita, Alface e Maionese',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'wrap-cogumelos',
          name: 'Wrap de Cogumelos',
          description: 'Cogumelos Salteados, Queijo, Rúcula, Cenoura e Molho de Alho',
          price: 6.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'wrap-salmao',
          name: 'Wrap de Salmão',
          description: 'Salmão, Cebola Frita, Queijo, Rúcula e Maionese',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'tostas-baguetes',
      category: 'Tostas e Baguetes',
      group: 'snacks',
      emoji: '🥙',
      items: [
        {
          id: 'tosta-mista',
          name: 'Tosta Mista',
          description: '',
          price: 3.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tosta-mista-pao-especial',
          name: 'Tosta Mista em Pão Especial',
          description: 'Pão Cereal / Nas / Alemão / Saloio',
          price: 4.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tosta-clave',
          name: 'Tosta à Clave',
          description: 'Ovo, Salsicha, Bacon, Queijo, Fiambre, Molho à Clave, Alface, Tomate',
          price: 8.00,
          tags: [],
          available: true,
          featured: true,
          image: '/images/menu/tosta_a_clave.png',
        },
        {
          id: 'tosta-frango',
          name: 'Tosta de Frango',
          description: 'Peito de Frango, Queijo Creme, Ovo, Alface, Tomate e Cebola',
          price: 8.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tosta-salmao',
          name: 'Tosta de Salmão',
          description: 'Salmão, Queijo Creme, Ovo, Rúcula, Alface, Tomate e Cebola',
          price: 8.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tosta-cogumelos',
          name: 'Tosta de Cogumelos',
          description: 'Cogumelos Frescos Salteados, Queijo, Rúcula e Molho de Alho',
          price: 8.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tosta-americana',
          name: 'Tosta Americana',
          description: 'Queijo, Fiambre, Ovo, Alface, Tomate e Maionese',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-delicias',
          name: 'Baguete de Delícias',
          description: 'Pasta de Delícias, Ovo, Alface e Tomate',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-atum',
          name: 'Baguete de Atum',
          description: 'Pasta de Atum, Ovo, Alface e Tomate',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-americana',
          name: 'Baguete Americana',
          description: 'Queijo, Fiambre, Ovo, Alface, Tomate e Maionese',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-frango',
          name: 'Baguete de Frango',
          description: 'Frango, Ovo, Queijo, Alface, Tomate e Maionese',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-vegetariana',
          name: 'Baguete Vegetariana',
          description: 'Cogumelos Frescos Salteados, Cebola Frita, Queijo, Tomate e Molho de Alho',
          price: 6.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-presunto-queijo',
          name: 'Baguete de Presunto e Queijo',
          description: '',
          price: 5.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'baguete-mista',
          name: 'Baguete Mista',
          description: '',
          price: 4.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'menu-kids',
      category: 'Menu Kids',
      group: 'manha',
      emoji: '👶',
      items: [
        {
          id: 'kids-salsicha',
          name: 'Salsicha',
          description: '',
          price: 6.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'kids-cheeseburger',
          name: 'Cheeseburger',
          description: '',
          price: 7.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'kids-peito-frango',
          name: 'Peito de Frango',
          description: '',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'kids-panado-frango',
          name: 'Panado de Frango',
          description: '',
          price: 7.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'kids-bife-lombo',
          name: 'Bife Lombo',
          description: '',
          price: 7.50,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'pequeno-almoco',
      category: 'Pequeno Almoço',
      group: 'manha',
      emoji: '☕',
      items: [
        {
          id: 'torrada',
          name: 'Torrada',
          description: '',
          price: 1.30,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'torrada-especial',
          name: 'Torrada Especial',
          description: 'Pão Cereal / Alemão / Nas / Saloio',
          price: 2.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'meia-torrada',
          name: 'Meia Torrada',
          description: '',
          price: 0.90,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'meia-torrada-especial',
          name: 'Meia Torrada Especial',
          description: 'Pão Cereal / Alemão / Nas / Saloio',
          price: 1.40,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'pastelaria-variada',
          name: 'Pastelaria Variada',
          description: '',
          price: 1.50,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'croissant',
          name: 'Croissant',
          description: '',
          price: 1.50,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'croissant-manteiga',
          name: 'Croissant com Manteiga',
          description: '',
          price: 2.00,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'croissant-queijo-fiambre',
          name: 'Croissant com Queijo ou Fiambre ou Nutella',
          description: '',
          price: 2.50,
          tags: ['vegetariano'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'croissant-misto',
          name: 'Croissant Misto',
          description: '',
          price: 3.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'tremocos',
          name: 'Tremoços',
          description: '',
          price: 1.00,
          tags: ['vegan', 'sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'amendoins',
          name: 'Amendoins',
          description: '',
          price: 1.00,
          tags: ['vegan', 'sem glúten'],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'prato-extra',
          name: 'Prato extra',
          description: '',
          price: 1.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'molho-extra',
          name: 'Molho extra',
          description: '',
          price: 1.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
        {
          id: 'ingrediente-extra',
          name: 'Ingrediente extra',
          description: '',
          price: 1.00,
          tags: [],
          available: true,
          featured: false,
          image: '',
        },
      ],
    },
    {
      id: 'bebidas',
      category: 'Bebidas',
      group: 'bebidas',
      emoji: '🍺',
      items: [
        {
          id: 'fino',
          name: 'Fino',
          description: '',
          price: 2.20,
          tags: ['vegan', 'sem glúten'],
          available: true,
          featured: false,
          image: '/images/menu/finos.png',
        },
        {
          id: 'sangria-maracuja',
          name: 'Sangria de Maracujá (2L)',
          description: '',
          price: 24.00,
          tags: ['vegan'],
          available: true,
          featured: true,
          image: '/images/menu/sangriamaracuja.png',
        },
      ],
    },
  ],

  // --- SEO ---
  seo: {
    title: 'Clave de Sol — Ementa Digital',
    description: 'Consulta a nossa ementa completa. Snacks, francesinhas, mariscos, hambúrgueres e muito mais. Since 1983.',
    ogImage: '/images/hero.jpg',
  },

  // --- AVISOS E NOTAS ---
  notes: [
    'Preços com IVA incluído.',
    'Disponibilidade sujeita a stock — *mediante disponibilidade*.',
    'Se for alérgico e em caso de dúvida, não hesite em consultar um colaborador nosso.',
  ],

  // --- ALLERGEN LEGEND ---
  tagLabels: {
    'vegan': '🌱 Vegan',
    'vegetariano': '🥬 Vegetariano',
    'sem glúten': '🌾 Sem Glúten',
    'picante': '🌶️ Picante',
  } as Record<string, string>,
};
