export const config = {
  name: 'Lip Food & Drinks',
  tagline: 'À Beira do Atlântico',
  description:
    'Bar de tapas e snacks na marginal de Caxinas, Vila do Conde. Os melhores petiscos acompanhados da melhor cerveja, com vista para o oceano Atlântico.',

  contact: {
    phone: '+351 919 578 448',
    phoneRaw: '351919578448',
    email: 'lip2022faceinsta@gmail.com',
    address: 'Av. Infante Dom Henrique, 680',
    city: 'Caxinas, Vila do Conde',
    postalCode: '4480-670',
    googleMapsUrl: 'https://maps.google.com/?q=41.3643896,-8.7605469',
    latitude: 41.3643896,
    longitude: -8.7605469,
    // Substitui este embed pelo link direto do Google Maps → Partilhar → Incorporar
    mapsEmbed:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d743.0!2d-8.7605469!3d41.3643896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDIxJzUxLjgiTiA4wrA0NSczOS44Ilc!5e0!3m2!1spt!2spt!4v1718700000000',
  },

  social: {
    instagram: 'https://www.instagram.com/lip_food.drinks/',
    facebook: 'https://www.facebook.com/lip.food.drinks/',
    whatsapp: 'https://wa.me/351919578448',
    whatsappReserva: 'https://wa.me/351919578448?text=Olá!%20Gostaria%20de%20fazer%20uma%20reserva%20de%20mesa.',
  },

  hours: [
    { day: 'Segunda-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Terça-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Quarta-feira', open: null, close: null, closed: true },
    { day: 'Quinta-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Sexta-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Sábado', open: '09:00', close: '00:00', closed: false },
    { day: 'Domingo', open: '09:00', close: '00:00', closed: false },
  ],

  features: [
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" /></svg>`,
      title: 'Vista para o Mar',
      desc: 'Esplanada com vista privilegiada para o oceano Atlântico na marginal de Caxinas',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15m-6.75-9.896c.251.023.501.05.75.082m0 0a24.301 24.301 0 00-4.5 0" /></svg>`,
      title: 'Petiscos Frescos',
      desc: 'Ingredientes frescos e locais, preparados no momento para a melhor experiência',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8.25v-1.5m0 1.5c-1.355 0-2.697.056-4.024.166C6.845 8.51 6 9.473 6 10.608v2.513m6-4.87c1.355 0 2.697.055 4.024.165C17.155 8.51 18 9.473 18 10.608v2.513m-3-4.87v-1.5m-6 4.5v4.5m6-4.5v4.5m6-8.25a48.11 48.11 0 00-6 0" /></svg>`,
      title: 'As Melhores Cervejas',
      desc: 'Seleção cuidada de cervejas nacionais e internacionais sempre geladas e fresquinhas',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007z" /></svg>`,
      title: 'Ambiente Descontraído',
      desc: 'O espaço perfeito para relaxar, petiscar e desfrutar de boa companhia',
    },
  ],

  menu: {
    categories: ['Petiscos', 'Pratos', 'Sobremesas', 'Bebidas'],
    items: [
      // Petiscos
      {
        id: 1,
        category: 'Petiscos',
        name: 'Camarão à Guilho',
        description: 'Camarão salteado em azeite, alho e coentros frescos',
        price: 12.5,
        emoji: '🦐',
        popular: true,
        available: true,
      },
      {
        id: 2,
        category: 'Petiscos',
        name: 'Rissóis de Camarão',
        description: '4 unidades, crocantes por fora e cremosos por dentro',
        price: 8.0,
        emoji: '🥟',
        popular: false,
        available: true,
      },
      {
        id: 3,
        category: 'Petiscos',
        name: 'Pataniscas de Bacalhau',
        description: 'Acompanhadas de arroz de tomate da casa',
        price: 9.5,
        emoji: '🐟',
        popular: true,
        available: true,
      },
      {
        id: 4,
        category: 'Petiscos',
        name: 'Alheira Grelhada',
        description: 'Com ovo a cavalo e batata frita caseira',
        price: 8.5,
        emoji: '🍳',
        popular: false,
        available: true,
      },
      {
        id: 5,
        category: 'Petiscos',
        name: 'Tosta Mista',
        description: 'Pão artesanal com fiambre e queijo fundido',
        price: 4.5,
        emoji: '🥪',
        popular: false,
        available: true,
      },
      {
        id: 6,
        category: 'Petiscos',
        name: 'Tábua Lip',
        description: 'Seleção da casa para partilhar — petiscos variados para 2 pessoas',
        price: 18.0,
        emoji: '🧆',
        popular: true,
        available: true,
      },
      // Pratos
      {
        id: 7,
        category: 'Pratos',
        name: 'Salmão Grelhado',
        description: 'Com legumes salteados e batata a murro',
        price: 14.0,
        emoji: '🐠',
        popular: true,
        available: true,
      },
      {
        id: 8,
        category: 'Pratos',
        name: 'Prego no Pão',
        description: 'Novilho com mostarda antiga, pickles e alface',
        price: 9.5,
        emoji: '🥩',
        popular: true,
        available: true,
      },
      {
        id: 9,
        category: 'Pratos',
        name: 'Francesinha Lip',
        description: 'A nossa versão especial com molho da casa',
        price: 13.5,
        emoji: '🫕',
        popular: true,
        available: true,
      },
      {
        id: 10,
        category: 'Pratos',
        name: 'Bifana',
        description: 'Lombo de porco com molho picante especial',
        price: 6.5,
        emoji: '🥙',
        popular: false,
        available: true,
      },
      {
        id: 11,
        category: 'Pratos',
        name: 'Hambúrguer Artesanal',
        description: 'Novilho, queijo, alface, tomate e batatas fritas',
        price: 12.0,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 12,
        category: 'Pratos',
        name: 'Salada César com Frango',
        description: 'Frango grelhado, croutons, parmesão e molho Caesar',
        price: 10.0,
        emoji: '🥗',
        popular: false,
        available: true,
      },
      // Sobremesas
      {
        id: 13,
        category: 'Sobremesas',
        name: 'Pastel de Nata',
        description: 'Artesanal, fresquinho com canela e açúcar em pó',
        price: 1.8,
        emoji: '🥐',
        popular: true,
        available: true,
      },
      {
        id: 14,
        category: 'Sobremesas',
        name: 'Mousse de Chocolate',
        description: 'Feita na casa, cremosa e intensa',
        price: 4.5,
        emoji: '🍫',
        popular: false,
        available: true,
      },
      {
        id: 15,
        category: 'Sobremesas',
        name: 'Bolo do Dia',
        description: 'Varia diariamente — pergunte ao balcão',
        price: 4.0,
        emoji: '🍰',
        popular: false,
        available: true,
      },
      // Bebidas
      {
        id: 16,
        category: 'Bebidas',
        name: 'Super Bock',
        description: '33cl garrafa, bem fresquinha',
        price: 2.0,
        emoji: '🍺',
        popular: false,
        available: true,
      },
      {
        id: 17,
        category: 'Bebidas',
        name: 'Imperial / Fino',
        description: 'Cerveja de pressão, sempre fresca',
        price: 1.5,
        emoji: '🍺',
        popular: true,
        available: true,
      },
      {
        id: 18,
        category: 'Bebidas',
        name: 'Sumo Natural',
        description: 'Laranja ou limão — espremido no momento',
        price: 3.5,
        emoji: '🍊',
        popular: true,
        available: true,
      },
      {
        id: 19,
        category: 'Bebidas',
        name: 'Refrigerante',
        description: 'Coca-Cola, Fanta, Sumol, 7Up — 33cl',
        price: 2.0,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 20,
        category: 'Bebidas',
        name: 'Água',
        description: 'Garrafa 50cl, com ou sem gás',
        price: 1.0,
        emoji: '💧',
        popular: false,
        available: true,
      },
      {
        id: 21,
        category: 'Bebidas',
        name: 'Café',
        description: 'Expresso curto ou longo',
        price: 0.8,
        emoji: '☕',
        popular: true,
        available: true,
      },
      {
        id: 22,
        category: 'Bebidas',
        name: 'Vinho da Casa',
        description: 'Branco, tinto ou rosé — copo',
        price: 3.0,
        emoji: '🍷',
        popular: false,
        available: true,
      },
    ],
  },

  seo: {
    title: 'Lip Food & Drinks — Snack Bar & Tapas em Caxinas, Vila do Conde',
    description:
      'Bar de tapas e petiscos na marginal de Caxinas, Vila do Conde. Os melhores snacks e bebidas com vista para o mar. Reserve uma mesa ou encomende online.',
    ogImage: '/images/og-image.jpg',
  },

  web3formsKey: 'YOUR_WEB3FORMS_KEY',
};
