export const config = {
  name: 'Lip Food & Drinks',
  tagline: 'À Beira do Atlântico',
  description:
    'Bar de tapas e snacks na marginal de Caxinas, Vila do Conde. Os melhores petiscos acompanhados da melhor cerveja, com vista para o oceano Atlântico.',

  contact: {
    phone: '+351 919 578 448',
    phoneRaw: '351919578448',
    email: 'lip2022faceinsta@gmail.com',
    address: 'Av. Infante Dom Henrique, 680',
    city: 'Caxinas, Vila do Conde',
    postalCode: '4480-670',
    googleMapsUrl: 'https://maps.google.com/?q=41.3643896,-8.7605469',
    latitude: 41.3643896,
    longitude: -8.7605469,
    mapsEmbed:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d743.0!2d-8.7605469!3d41.3643896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDIxJzUxLjgiTiA4wrA0NSczOS44Ilc!5e0!3m2!1spt!2spt!4v1718700000000',
  },

  social: {
    instagram: 'https://www.instagram.com/lip_food.drinks/',
    facebook: 'https://www.facebook.com/lip.food.drinks/',
    whatsapp: 'https://wa.me/351919578448',
    whatsappReserva: 'https://wa.me/351919578448?text=Olá!%20Gostaria%20de%20fazer%20uma%20reserva%20de%20mesa.',
  },

  hours: [
    { day: 'Segunda-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Terça-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Quarta-feira', open: null, close: null, closed: true },
    { day: 'Quinta-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Sexta-feira', open: '09:00', close: '00:00', closed: false },
    { day: 'Sábado', open: '09:00', close: '00:00', closed: false },
    { day: 'Domingo', open: '09:00', close: '00:00', closed: false },
  ],

  features: [
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" /></svg>`,
      title: 'Vista para o Mar',
      desc: 'Esplanada com vista privilegiada para o oceano Atlântico na marginal de Caxinas',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15m-6.75-9.896c.251.023.501.05.75.082m0 0a24.301 24.301 0 00-4.5 0" /></svg>`,
      title: 'Petiscos Frescos',
      desc: 'Ingredientes frescos e locais, preparados no momento para a melhor experiência',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8.25v-1.5m0 1.5c-1.355 0-2.697.056-4.024.166C6.845 8.51 6 9.473 6 10.608v2.513m6-4.87c1.355 0 2.697.055 4.024.165C17.155 8.51 18 9.473 18 10.608v2.513m-3-4.87v-1.5m-6 4.5v4.5m6-4.5v4.5m6-8.25a48.11 48.11 0 00-6 0" /></svg>`,
      title: 'As Melhores Cervejas',
      desc: 'Seleção cuidada de cervejas nacionais e internacionais sempre geladas e fresquinhas',
    },
    {
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007z" /></svg>`,
      title: 'Ambiente Descontraído',
      desc: 'O espaço perfeito para relaxar, petiscar e desfrutar de boa companhia',
    },
  ],

  menu: {
    categories: ['Entradas', 'Snacks', 'Saladas', 'Baguetes & Tostas', 'Hambúrgueres & Wraps', 'Acompanhamentos', 'Sobremesas', 'Bebidas'],
    items: [
      // ── Entradas ──────────────────────────────────────────────────────────
      {
        id: 1,
        category: 'Entradas',
        name: 'Pão de Alho com Bacon',
        description: '4 fatias de pão de alho com tiras de bacon por cima.',
        price: 7.00,
        emoji: '🧄',
        popular: true,
        available: true,
      },
      {
        id: 2,
        category: 'Entradas',
        name: 'Ameijoas',
        description: 'Ameijoas na concha com ervas, servidas como entrada de marisco.',
        price: 16.50,
        emoji: '🦪',
        popular: false,
        available: true,
      },
      {
        id: 3,
        category: 'Entradas',
        name: 'Asinhas de Frango',
        description: 'Porção de asinhas de frango, acompanhadas de molho para mergulhar.',
        price: 10.00,
        emoji: '🍗',
        popular: true,
        available: true,
      },
      {
        id: 4,
        category: 'Entradas',
        name: 'Camarão Crocante',
        description: 'Camarões enrolados em massa fina e crocante.',
        price: 12.10,
        emoji: '🦐',
        popular: false,
        available: true,
      },
      {
        id: 5,
        category: 'Entradas',
        name: 'Gambas à LIP',
        description: 'Gambas em molho especial da casa com lâminas de alho.',
        price: 16.50,
        emoji: '🦐',
        popular: true,
        available: true,
      },
      {
        id: 6,
        category: 'Entradas',
        name: 'Ovos Rotos',
        description: 'Batatas fritas, presunto e ovos estrelados.',
        price: 8.70,
        emoji: '🍳',
        popular: false,
        available: true,
      },
      {
        id: 7,
        category: 'Entradas',
        name: 'Ovos Rotos à LIP',
        description: 'Gambas, cogumelos salteados, ovos, batatas fritas e queijo.',
        price: 12.10,
        emoji: '🍳',
        popular: false,
        available: true,
      },
      {
        id: 8,
        category: 'Entradas',
        name: 'Tosta Gratinada (Pizza)',
        description: 'Molho basílico, azeitonas, cebola, cogumelos, pimentos e queijo.',
        price: 10.10,
        emoji: '🍕',
        popular: false,
        available: true,
      },
      {
        id: 9,
        category: 'Entradas',
        name: 'Tosta Gratinada de Atum',
        description: 'Molho basílico, azeitonas, cebola, atum e queijo.',
        price: 10.10,
        emoji: '🐟',
        popular: false,
        available: true,
      },
      {
        id: 10,
        category: 'Entradas',
        name: 'Alheira no Forno',
        description: 'Enchido de alheira tradicional assado no forno.',
        price: 6.20,
        emoji: '🌭',
        popular: false,
        available: true,
      },
      {
        id: 11,
        category: 'Entradas',
        name: 'Rissóis Leitão (2 unidades)',
        description: '2 rissóis panados com recheio de leitão desfiado.',
        price: 6.20,
        emoji: '🥟',
        popular: false,
        available: true,
      },

      // ── Snacks ────────────────────────────────────────────────────────────
      {
        id: 12,
        category: 'Snacks',
        name: 'Francesinha Normal',
        description: 'Queijo, fiambre, chourição, ketchup, maionese e mostarda.',
        price: 7.50,
        emoji: '🫕',
        popular: true,
        available: true,
      },
      {
        id: 13,
        category: 'Snacks',
        name: 'Francesinha Normal à LIP',
        description: 'Queijo, fiambre, chourição, ketchup, maionese, mostarda, batatas fritas e molho especial.',
        price: 12.10,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 14,
        category: 'Snacks',
        name: 'Francesinha Poveira',
        description: 'Queijo, fiambre, linguiça, ketchup, maionese e mostarda.',
        price: 7.50,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 15,
        category: 'Snacks',
        name: 'Francesinha Poveira à LIP',
        description: 'Queijo, fiambre, linguiça, ketchup, maionese, mostarda, batatas fritas e molho especial.',
        price: 12.10,
        emoji: '🫕',
        popular: true,
        available: true,
      },
      {
        id: 16,
        category: 'Snacks',
        name: 'Cachorro Normal',
        description: 'Queijo, fiambre, salsicha, ketchup, maionese e mostarda.',
        price: 7.50,
        emoji: '🌭',
        popular: false,
        available: true,
      },
      {
        id: 17,
        category: 'Snacks',
        name: 'Cachorro à LIP',
        description: 'Queijo, fiambre, salsicha, ketchup, maionese, mostarda, batatas fritas e molho especial.',
        price: 12.10,
        emoji: '🌭',
        popular: true,
        available: true,
      },
      {
        id: 18,
        category: 'Snacks',
        name: 'Francesinha Especial',
        description: 'Alcatra, queijo, fiambre, chourição, ovo e molho especial.',
        price: 14.70,
        emoji: '🫕',
        popular: true,
        available: true,
      },
      {
        id: 19,
        category: 'Snacks',
        name: 'Francesinha Especial de Frango',
        description: 'Francesinha de frango com camadas de pão, coberta com queijo derretido, ovo e molho especial.',
        price: 13.40,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 20,
        category: 'Snacks',
        name: 'Francesinha Especial de Lombo',
        description: 'Lombo, queijo, fiambre, linguiça, ovo e molho especial.',
        price: 19.20,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 21,
        category: 'Snacks',
        name: 'Francesinha Vegetariana',
        description: 'Queijo, cogumelos salteados, alho francês, curgete, ananás, ovo e molho especial.',
        price: 14.00,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 22,
        category: 'Snacks',
        name: 'Francesinha Especial Alheira',
        description: 'Alheira, queijo, fiambre, chourição, ovo e molho especial.',
        price: 14.70,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 23,
        category: 'Snacks',
        name: 'Pica Pau',
        description: 'Lombo, linguiça, bacon, salsicha, chourição e pickles.',
        price: 14.70,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 24,
        category: 'Snacks',
        name: 'Prego em Pão com Ovo e Bacon',
        description: 'Lombo, queijo, bacon, ovo, bolo do caco e manteiga de alho.',
        price: 14.00,
        emoji: '🥩',
        popular: true,
        available: true,
      },
      {
        id: 25,
        category: 'Snacks',
        name: 'Prego em Prato',
        description: 'Alcatra, bacon, alface, tomate, cenoura, ovo e batatas fritas.',
        price: 14.00,
        emoji: '🥩',
        popular: true,
        available: true,
      },
      {
        id: 26,
        category: 'Snacks',
        name: 'P.O',
        description: 'Presunto, ovo e queijo.',
        price: 6.60,
        emoji: '🍳',
        popular: false,
        available: true,
      },
      {
        id: 27,
        category: 'Snacks',
        name: 'Francesinha Especial à Chef',
        description: 'Lombo, cheddar, bacon, linguiça, ovo e molho especial.',
        price: 22.50,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 28,
        category: 'Snacks',
        name: 'Prego em Pão Lombo',
        description: 'Lombo, queijo, fiambre, bolo do caco e manteiga de alho.',
        price: 12.80,
        emoji: '🥩',
        popular: true,
        available: true,
      },
      {
        id: 29,
        category: 'Snacks',
        name: 'Prego em Pão com Cogumelos',
        description: 'Lombo, queijo, cogumelos salteados, bolo do caco, molho de alho e manteiga de alho.',
        price: 13.40,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 30,
        category: 'Snacks',
        name: 'Prego de Seia',
        description: 'Lombo, queijo de seia e bolo do caco.',
        price: 14.00,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 31,
        category: 'Snacks',
        name: 'Prego em Prato Lombo',
        description: 'Lombo, bacon, alface, tomate, cenoura, ovo e batatas fritas.',
        price: 18.60,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 32,
        category: 'Snacks',
        name: 'Alheira no Prato',
        description: 'Alheira, bacon, alface, tomate, cenoura, ovo e batatas fritas.',
        price: 14.00,
        emoji: '🍽️',
        popular: false,
        available: true,
      },
      {
        id: 33,
        category: 'Snacks',
        name: 'Bife à LIP',
        description: 'Alcatra, queijo, fiambre, ovo, batatas fritas e molho especial.',
        price: 16.60,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 34,
        category: 'Snacks',
        name: 'Bife do Lombo à LIP',
        description: 'Lombo, queijo, fiambre, ovo, batatas fritas e molho especial.',
        price: 21.80,
        emoji: '🥩',
        popular: false,
        available: true,
      },
      {
        id: 35,
        category: 'Snacks',
        name: 'Alheira à LIP',
        description: 'Alheira, queijo, fiambre, ovo, batatas fritas e molho especial.',
        price: 16.60,
        emoji: '🍽️',
        popular: false,
        available: true,
      },
      {
        id: 36,
        category: 'Snacks',
        name: 'Meia Francesinha Especial',
        description: 'Alcatra, queijo, fiambre, chourição, ovo e molho especial.',
        price: 10.80,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 37,
        category: 'Snacks',
        name: 'Meia Francesinha Especial Frango',
        description: 'Frango, queijo, fiambre frango, chourição, ovo e molho especial.',
        price: 10.10,
        emoji: '🫕',
        popular: false,
        available: true,
      },
      {
        id: 38,
        category: 'Snacks',
        name: 'Meia Francesinha Especial Lombo',
        description: 'Lombo, queijo, fiambre, linguiça, ovo e molho especial.',
        price: 15.30,
        emoji: '🫕',
        popular: false,
        available: true,
      },

      // ── Saladas ───────────────────────────────────────────────────────────
      {
        id: 39,
        category: 'Saladas',
        name: 'Salada de Camarão e Delícias',
        description: 'Camarões, delícias, alface, rúcula, cenoura, milho, queijo fresco, ovo, crutons, molho iogurte e orégãos.',
        price: 12.10,
        emoji: '🥗',
        popular: true,
        available: true,
      },
      {
        id: 40,
        category: 'Saladas',
        name: 'Salada de Frango',
        description: 'Frango, alface, rúcula, cenoura, milho, queijo fresco, ovo, crutons, molho iogurte e orégãos.',
        price: 12.10,
        emoji: '🥗',
        popular: false,
        available: true,
      },
      {
        id: 41,
        category: 'Saladas',
        name: 'Salada de Atum',
        description: 'Atum, alface, rúcula, cenoura, milho, queijo fresco, ovo, crutons, molho iogurte e orégãos.',
        price: 12.10,
        emoji: '🥗',
        popular: true,
        available: true,
      },
      {
        id: 42,
        category: 'Saladas',
        name: 'Salada de Salmão',
        description: 'Salmão fumado, alface, rúcula, cenoura, milho, queijo fresco, ovo, crutons, molho iogurte e orégãos.',
        price: 12.10,
        emoji: '🥗',
        popular: false,
        available: true,
      },

      // ── Baguetes & Tostas ─────────────────────────────────────────────────
      {
        id: 43,
        category: 'Baguetes & Tostas',
        name: 'Baguete de Atum',
        description: 'Pasta de atum, alface, tomate e ovo.',
        price: 7.90,
        emoji: '🥖',
        popular: true,
        available: true,
      },
      {
        id: 44,
        category: 'Baguetes & Tostas',
        name: 'Baguete de Delícias',
        description: 'Pasta de delícias, alface, tomate e ovo.',
        price: 7.90,
        emoji: '🥖',
        popular: true,
        available: true,
      },
      {
        id: 45,
        category: 'Baguetes & Tostas',
        name: 'Baguete de Frango',
        description: 'Frango, queijo, alface, tomate, ovo e maionese.',
        price: 8.60,
        emoji: '🥖',
        popular: false,
        available: true,
      },
      {
        id: 46,
        category: 'Baguetes & Tostas',
        name: 'Baguete Americana',
        description: 'Queijo, fiambre, alface, tomate, ovo e maionese.',
        price: 7.50,
        emoji: '🥖',
        popular: true,
        available: true,
      },
      {
        id: 47,
        category: 'Baguetes & Tostas',
        name: 'Baguete de Presunto e Queijo',
        description: 'Presunto, queijo e baguete.',
        price: 6.90,
        emoji: '🥖',
        popular: false,
        available: true,
      },
      {
        id: 48,
        category: 'Baguetes & Tostas',
        name: 'Tosta de Cogumelos',
        description: 'Cogumelos salteados, rúcula, queijo, molho de alho e pão alentejano.',
        price: 10.80,
        emoji: '🍞',
        popular: true,
        available: true,
      },
      {
        id: 49,
        category: 'Baguetes & Tostas',
        name: 'Tosta Mista',
        description: 'Queijo e fiambre.',
        price: 5.20,
        emoji: '🍞',
        popular: true,
        available: true,
      },
      {
        id: 50,
        category: 'Baguetes & Tostas',
        name: 'Tosta Mista em Pão Alentejano',
        description: 'Queijo, fiambre e pão alentejano.',
        price: 6.00,
        emoji: '🍞',
        popular: false,
        available: true,
      },
      {
        id: 51,
        category: 'Baguetes & Tostas',
        name: 'Tosta à LIP',
        description: 'Salsicha, bacon, ovo, queijo, fiambre, alface, tomate e molho da casa.',
        price: 10.80,
        emoji: '🍞',
        popular: true,
        available: true,
      },
      {
        id: 52,
        category: 'Baguetes & Tostas',
        name: 'Tosta de Frango',
        description: 'Frango, queijo creme, alface, tomate, cebola, ovo e pão alentejano.',
        price: 10.80,
        emoji: '🍞',
        popular: false,
        available: true,
      },
      {
        id: 53,
        category: 'Baguetes & Tostas',
        name: 'Tosta de Salmão',
        description: 'Salmão fumado, queijo creme, rúcula, tomate, cebola, ovo e pão alentejano.',
        price: 10.80,
        emoji: '🍞',
        popular: false,
        available: true,
      },
      {
        id: 54,
        category: 'Baguetes & Tostas',
        name: 'Tosta Americana',
        description: 'Queijo, fiambre, alface, tomate, cebola, ovo, maionese e pão alentejano.',
        price: 9.50,
        emoji: '🍞',
        popular: false,
        available: true,
      },

      // ── Hambúrgueres & Wraps ──────────────────────────────────────────────
      {
        id: 55,
        category: 'Hambúrgueres & Wraps',
        name: 'Cheddar Burger',
        description: 'Hambúrguer de novilho 220g, extra queijo cheddar, bacon, cebola frita, ovo e molho burguer.',
        price: 13.40,
        emoji: '🍔',
        popular: true,
        available: true,
      },
      {
        id: 56,
        category: 'Hambúrgueres & Wraps',
        name: 'Hambúrguer no Pão',
        description: 'Hambúrguer de novilho 170g, queijo, fiambre, alface, tomate, ketchup, maionese e mostarda.',
        price: 9.90,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 57,
        category: 'Hambúrgueres & Wraps',
        name: 'Hambúrguer de Frango no Pão',
        description: 'Hambúrguer de frango, queijo, fiambre frango, alface, tomate e molho da casa.',
        price: 9.90,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 58,
        category: 'Hambúrgueres & Wraps',
        name: 'Hambúrguer à Chef',
        description: 'Hambúrguer de novilho 170g, queijo, bacon, rúcula, tomate, cebola frita, ovo e molho de tosta.',
        price: 11.20,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 59,
        category: 'Hambúrgueres & Wraps',
        name: 'Hambúrguer à LIP',
        description: 'Hambúrguer de novilho 170g, queijo cheddar, bacon, rúcula, cebola frita, cogumelos salteados, ovo, molho barbecue e manteiga de alho.',
        price: 12.10,
        emoji: '🍔',
        popular: true,
        available: true,
      },
      {
        id: 60,
        category: 'Hambúrgueres & Wraps',
        name: 'Beyond Burger® Vegetariano',
        description: 'Beyond Burger®, alface, tomate, cebola, manteiga de alho e molho de alho.',
        price: 10.20,
        emoji: '🌿',
        popular: false,
        available: true,
      },
      {
        id: 61,
        category: 'Hambúrgueres & Wraps',
        name: 'Big LIP',
        description: '2 hambúrgueres de novilho 130g, alface, cebola picada, pickles e molho de hambúrguer.',
        price: 12.70,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 62,
        category: 'Hambúrgueres & Wraps',
        name: 'Brie Burger',
        description: 'Hambúrguer de novilho 170g, queijo brie, doce de abóbora, tomate grelhado e agrião.',
        price: 11.20,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 63,
        category: 'Hambúrgueres & Wraps',
        name: 'Hambúrguer à Caçador',
        description: 'Hambúrguer de novilho 170g, alheira, ovo, molho agridoce e agrião.',
        price: 12.10,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 64,
        category: 'Hambúrgueres & Wraps',
        name: 'RJ Burger',
        description: 'Pão brioche, maionese de bacon, 2 hambúrgueres de picanha 130g, alface, cebola, bacon, queijo cheddar.',
        price: 14.00,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 65,
        category: 'Hambúrgueres & Wraps',
        name: 'Wrap de Frango',
        description: 'Frango, queijo cheddar, alface, cebola frita e maionese.',
        price: 7.40,
        emoji: '🌯',
        popular: true,
        available: true,
      },
      {
        id: 66,
        category: 'Hambúrgueres & Wraps',
        name: 'Wrap de Cogumelos',
        description: 'Cogumelos salteados, queijo, cenoura, rúcula e molho de alho.',
        price: 7.40,
        emoji: '🌯',
        popular: false,
        available: true,
      },
      {
        id: 67,
        category: 'Hambúrgueres & Wraps',
        name: 'Wrap de Camarão',
        description: 'Gambas salteadas com pimentos e cebola, queijo e alface.',
        price: 7.40,
        emoji: '🌯',
        popular: false,
        available: true,
      },
      {
        id: 68,
        category: 'Hambúrgueres & Wraps',
        name: 'Wrap de Salmão',
        description: 'Salmão fumado, queijo, rúcula, cebola frita e maionese.',
        price: 7.40,
        emoji: '🌯',
        popular: false,
        available: true,
      },

      // ── Acompanhamentos ───────────────────────────────────────────────────
      {
        id: 69,
        category: 'Acompanhamentos',
        name: 'Arroz',
        description: 'Porção de arroz como acompanhamento.',
        price: 4.50,
        emoji: '🍚',
        popular: false,
        available: true,
      },
      {
        id: 70,
        category: 'Acompanhamentos',
        name: 'Batata (Dose)',
        description: 'Porção de batata servida como acompanhamento.',
        price: 4.50,
        emoji: '🍟',
        popular: true,
        available: true,
      },
      {
        id: 71,
        category: 'Acompanhamentos',
        name: 'Batata Rústica (Dose)',
        description: 'Batatas rústicas em gomos, com casca.',
        price: 5.60,
        emoji: '🍟',
        popular: false,
        available: true,
      },
      {
        id: 72,
        category: 'Acompanhamentos',
        name: 'Batata Doce (Dose)',
        description: 'Porção de batata-doce como acompanhamento.',
        price: 7.50,
        emoji: '🍠',
        popular: false,
        available: true,
      },
      {
        id: 73,
        category: 'Acompanhamentos',
        name: 'Batatas Especiais',
        description: 'Batatas fritas, queijo e molho especial.',
        price: 7.50,
        emoji: '🍟',
        popular: true,
        available: true,
      },
      {
        id: 74,
        category: 'Acompanhamentos',
        name: 'Batatas à LIP',
        description: 'Batatas fritas, queijo cheddar e bacon.',
        price: 8.60,
        emoji: '🍟',
        popular: false,
        available: true,
      },
      {
        id: 75,
        category: 'Acompanhamentos',
        name: 'Salsicha (Kids)',
        description: 'Dose infantil de salsicha.',
        price: 7.60,
        emoji: '🌭',
        popular: false,
        available: true,
      },
      {
        id: 76,
        category: 'Acompanhamentos',
        name: 'Hambúrguer (Kids)',
        description: 'Porção infantil de hambúrguer.',
        price: 8.90,
        emoji: '🍔',
        popular: false,
        available: true,
      },
      {
        id: 77,
        category: 'Acompanhamentos',
        name: 'Bife de Alcatra (Kids)',
        description: 'Dose infantil de bife de alcatra.',
        price: 8.90,
        emoji: '🥩',
        popular: true,
        available: true,
      },
      {
        id: 78,
        category: 'Acompanhamentos',
        name: 'Bife de Frango (Kids)',
        description: 'Porção infantil de bife de frango.',
        price: 8.90,
        emoji: '🍗',
        popular: false,
        available: true,
      },

      // ── Sobremesas ────────────────────────────────────────────────────────
      {
        id: 79,
        category: 'Sobremesas',
        name: 'Waffle com Açúcar e Canela',
        description: 'Waffle tradicional, polvilhado com açúcar e canela.',
        price: 7.50,
        emoji: '🧇',
        popular: true,
        available: true,
      },
      {
        id: 80,
        category: 'Sobremesas',
        name: 'Waffle com Nutella',
        description: 'Waffle com creme de avelã e cacau Nutella.',
        price: 8.80,
        emoji: '🧇',
        popular: false,
        available: true,
      },

      // ── Bebidas ───────────────────────────────────────────────────────────
      {
        id: 81,
        category: 'Bebidas',
        name: 'Coca-Cola 33cl',
        description: 'Lata de Coca-Cola 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 82,
        category: 'Bebidas',
        name: 'Coca-Cola Zero 33cl',
        description: 'Lata de Coca-Cola Zero 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 83,
        category: 'Bebidas',
        name: '7UP 33cl',
        description: 'Lata de 7UP 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 84,
        category: 'Bebidas',
        name: 'Fanta 33cl',
        description: 'Lata de Fanta 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 85,
        category: 'Bebidas',
        name: 'Guaraná 33cl',
        description: 'Lata de Guaraná 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 86,
        category: 'Bebidas',
        name: 'Sumol 33cl',
        description: 'Lata de Sumol 33cl.',
        price: 2.80,
        emoji: '🥤',
        popular: false,
        available: true,
      },
      {
        id: 87,
        category: 'Bebidas',
        name: 'Ice Tea 33cl',
        description: 'Lata de Ice Tea 33cl.',
        price: 2.80,
        emoji: '🍵',
        popular: true,
        available: true,
      },
      {
        id: 88,
        category: 'Bebidas',
        name: 'Somersby Frutos Vermelhos 33cl',
        description: 'Cidra com sabor a frutos vermelhos 33cl.',
        price: 4.50,
        emoji: '🍺',
        popular: false,
        available: true,
      },
      {
        id: 89,
        category: 'Bebidas',
        name: 'Pedras 25cl',
        description: 'Água com gás Pedras 25cl.',
        price: 2.00,
        emoji: '💧',
        popular: false,
        available: true,
      },
      {
        id: 90,
        category: 'Bebidas',
        name: 'Pedras Sabores 25cl',
        description: 'Água com gás Pedras com sabor 25cl.',
        price: 2.50,
        emoji: '💧',
        popular: false,
        available: true,
      },
      {
        id: 91,
        category: 'Bebidas',
        name: 'Frize 25cl',
        description: 'Água com gás Frize 25cl.',
        price: 2.50,
        emoji: '💧',
        popular: false,
        available: true,
      },
      {
        id: 92,
        category: 'Bebidas',
        name: 'Água 50cl',
        description: 'Garrafa de água 50cl.',
        price: 1.60,
        emoji: '💧',
        popular: false,
        available: true,
      },
      {
        id: 93,
        category: 'Bebidas',
        name: 'Super Bock 33cl',
        description: 'Garrafa de Super Bock 33cl.',
        price: 2.90,
        emoji: '🍺',
        popular: true,
        available: true,
      },
      {
        id: 94,
        category: 'Bebidas',
        name: 'Corona 35cl',
        description: 'Garrafa de Corona 35cl.',
        price: 4.20,
        emoji: '🍺',
        popular: false,
        available: true,
      },
      {
        id: 95,
        category: 'Bebidas',
        name: 'Pobeira Beach Lager 33cl',
        description: 'Cerveja artesanal local Pobeira Beach Lager 33cl.',
        price: 4.20,
        emoji: '🍺',
        popular: false,
        available: true,
      },
      {
        id: 96,
        category: 'Bebidas',
        name: 'Pobeira Nata Stout 33cl',
        description: 'Cerveja artesanal local Pobeira Nata Stout 33cl.',
        price: 4.20,
        emoji: '🍺',
        popular: false,
        available: true,
      },
      {
        id: 97,
        category: 'Bebidas',
        name: 'Leffe Bruin 33cl',
        description: 'Cerveja belga Leffe Bruin 33cl.',
        price: 5.50,
        emoji: '🍺',
        popular: false,
        available: true,
      },
    ],
  },

  seo: {
    title: 'Lip Food & Drinks — Snack Bar & Tapas em Caxinas, Vila do Conde',
    description:
      'Bar de tapas e petiscos na marginal de Caxinas, Vila do Conde. Os melhores snacks e bebidas com vista para o mar. Reserve uma mesa ou encomende online.',
    ogImage: '/images/og-image.jpg',
  },

  web3formsKey: 'YOUR_WEB3FORMS_KEY',
};
